### ISSUE TITLE
Issues on On AWS , DigitalOcean and Meteor.com on Ubuntu Server

### ISSUE THREAD

**Issue by sbollampalli** [ryanswapp/meteor-pdf-tutorial#1]
Was successfully able to execute this on local windows box. But when I moved the same code on to any of the above cloud hosting services ran into issue of spawn: ENOENT not sure why. 

Did anyone run into same issue.

**Comment by sbollampalli** [comment]
Above Issue is when these lines are executed.
webshot(html_string, fileName, options, function(err) {
  fs.readFile(fileName, function (err, data) {
     if (err) {
        return console.log(err);
     }

```
 fs.unlinkSync(fileName);
 fut.return(data);
```

  });
});

**Comment by ryanswapp** [comment]
Do you have the full error code that you can share? I suspect that you're getting that error because the code can't find your server's tmp directory (where webshot temporarily stores the new pdf).

**Comment by bsrikanth0805** [comment]
Here is the exact error from logs 

events.js:72
    throw er; // Unhandled 'error' event

Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
error: Forever detected script exited with code: 8
error: Script restart attempt #1

**Comment by sbollampalli** [comment]
Above Error is the exact error which I get too. I have tried even commenting all the lines of code within below snippet still I get the error above. I think it's something to do with invoking webshot

 webshot(html_string, fileName, options, function(err) {
        // console.log("----------WEBSHOT-----------2");
        //   fs.readFile(fileName, function (err, data) {
        //       if (err) {
        //           return console.log(err);
        //       }
        //       fs.unlinkSync(fileName);
        //       fut.return(data);
        //   });
  });

**Comment by ryanswapp** [comment]
Hmm... I really have no idea as to what is going on without more info. Maybe your production environment isn't loading npm modules?

**Comment by sbollampalli** [comment]
I would dig in more and see If I can find a solution.

Thanks for putting this article together it sure helped me in learning more on meteor.

**Comment by mlecoq** [comment]
I have the same issue with webshot on my aws server. Any idea ?

**Comment by lpamdfk** [comment]
I'm having the exact same issue. Did anyone solve this?

**Comment by ryanswapp** [comment]
@lpamdfk Are you using Meteor 1.3? When I upgraded I initially had some issues with webshot. The issue was that the phantomjs binary wasn't being built for the production environment and thus causing the app to crash. I was using mup at the time and decided to try mupx on a whim. Surprisingly enough it appears that mupx solved the issue because it was able to properly build the binary for the docker environment. I don't know if that is your issue but figured I'd share just in case.

**Comment by lpamdfk** [comment]
@ryanswapp Yes I'm using Meteor 1.3. I'm also using mupx with the deployment, but can't get this to work. I tried the 0.16.0 and 0.18.0 webshot versions, and the phantomjs modules that are being installed with them (phantomjs-prebuilt). I'm also wondering if I still need to use the dfischer:phantomjs package at this point, with latest Meteor version and when the 'native' phantomjs is being installed on node modules with webshot. I tried it with and without - works both ways in local environment but not on Digital Ocean Ubuntu. Everything else works as expected but I'm struggling with this.

edit:

Okay so I got it working now somehow. First, whenever I installed webshot, phantomjs-prebuilt was installed also to the node_modules. It was also installed to webshot/lib/node_modules, as it should I think. Now what I did on the servers docker environment, I uninstalled these two phantomjs-prebuilt instances, and then it started working... I'm not sure what's going on here. Does the mupx set up phantomjs automatically somewhere, and my 'own' phantomjs module was conflicting with that somehow. Btw, the styling is looking very different with the generated reports on the server, but that's a different matter altogether.

**Comment by IDCOLL** [comment]
@Ipamdfk, you mentioned in your last post that you sorted this problem by uninstalling the phatomjs-prebuilt instances in the docker environment. How do you actually do it?
