### ISSUE TITLE
Webshot error 'indexOf' 

### ISSUE THREAD

**Issue by felipesmendes** [ryanswapp/meteor-pdf-tutorial#4]
Hello Ryan, 

I moved the meteor-pdf-tutorial code to my application and is this what I have:

private/ 
**pdfLayout.html**

```
{{{getDocType}}}
<html lang="en">
<head>
    <style type="text/css">
        {{css}}
    </style>
</head>
<body>

  {{> Template.dynamic template=template data=data}}

</body>
</html>
```

**posicoes.html**

```
<table class="ui celled table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Status</th>
      <th>Notes</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>No Name Specified</td>
      <td>Unknown</td>
      <td class="negative">None</td>
    </tr>
    <tr class="positive">
      <td>Jimmy</td>
      <td><i class="icon checkmark"></i> Approved</td>
      <td>None</td>
    </tr>
    <tr>
      <td>Jamie</td>
      <td>Unknown</td>
      <td class="positive"><i class="icon close"></i> Requires call</td>
    </tr>
    <tr class="negative">
      <td>Jill</td>
      <td>Unknown</td>
      <td>None</td>
    </tr>
  </tbody>
</table>
```

**and the meteor method** 

```
'gerarPdf': function() {
    // SETUP
    // Grab required packages
    var webshot = require('webshot');
    var fs = require('fs');
    var Future = require('fibers/future');

    var fut = new Future();

    var fileName = "relatorio.pdf";

    // GENERATE HTML STRING
    var css = Assets.getText('style.css');

    SSR.compileTemplate('pdfLayout', Assets.getText('pdfLayout.html'));

    Template.pdfLayout.helpers({
      getDocType: function() {
        return "<!DOCTYPE html>";
      }
    });
    SSR.compileTemplate('posicoesPdf', Assets.getText('posicoes.html'));

    var html_string = SSR.render('pdfLayout', {
      css: css,
      template: "posicoesPdf",
      data: {}
    });
    // Setup Webshot options
    var options = {
      "paperSize": {
        "format": "Letter",
        "orientation": "portrait",
        "margin": "1cm"
      },
      siteType: 'html'
    };

    // Commence Webshot
    console.log("Commencing webshot...");
    webshot(html_string, fileName, options, function(err) {
      fs.readFile(fileName, function(err, data) {
        console.log(data);
        if (err) {
          return console.log(err);
        }

        fs.unlinkSync(fileName);
        fut.return(data);

      });
    });

    let pdfData = fut.wait();
    let base64String = new Buffer(pdfData).toString('base64');

    return base64String;
  }
```

and styles.css is just semantic ui css lib.

I'm getting this error when I call the method:

```
TypeError: Cannot call method 'indexOf' of null
     at readShebang (C:\Users\felipe\Documents\tracker\node_modules\cross-spawn\index.js:16:17)
     at Function.spawn (C:\Users\felipe\Documents\tracker\node_modules\cross-spawn\index.js:91:15)
     at spawnPhantom (C:\Users\felipe\Documents\tracker\node_modules\webshot\lib\webshot.js:201:32)
     at spawn (C:\Users\felipe\Documents\tracker\node_modules\webshot\lib\webshot.js:105:14)
     at spawn (C:\Users\felipe\Documents\tracker\node_modules\webshot\lib\webshot.js:103:14)
     at C:\Users\felipe\Documents\tracker\node_modules\webshot\lib\webshot.js:117:16
     at Object.cb [as oncomplete] (evalmachine.<anonymous>:169:19)
```

Could you please take a look and try to help me?
Thank you so much.

**Comment by felipesmendes** [comment]
Problem solved...missing fibers and phantomjs.

**Comment by ryanswapp** [comment]
@felipesmendes Hey I apologize for not getting back to you yesterday. I've got some crazy stuff going on at work and it's requiring a lot of my attention. I'm glad you got it figured out!
